# -*- coding: utf-8 -*-

import re
import json


res_list = []




def parse_season(text2):
    text2 = text2.replace(u'第一季', u'第1季')
    text2 = text2.replace(u'第二季', u'第2季')
    text2 = text2.replace(u'第三季', u'第3季')
    text2 = text2.replace(u'第四季', u'第4季')
    text2 = text2.replace(u'第五季', u'第5季')
    text2 = text2.replace(u'第六季', u'第6季')
    text2 = text2.replace(u'第七季', u'第7季')
    text2 = text2.replace(u'第八季', u'第8季')
    text2 = text2.replace(u'第九季', u'第9季')
    text2 = text2.replace(u'第十季', u'第10季')
    text2 = text2.replace(u'第十一季', u'第11季')
    text2 = text2.replace(u'第十二季', u'第12季')
    text2 = text2.replace(u'第十三季', u'第13季')
    text2 = text2.replace(u'第十四季', u'第14季')
    text2 = text2.replace(u'第十五季', u'第15季')
    text2 = text2.replace(u'第十六季', u'第16季')
    text2 = text2.replace(u'第十七季', u'第17季')
    text2 = text2.replace(u'第十八季', u'第18季')
    text2 = text2.replace(u'第十九季', u'第19季')
    text2 = text2.replace(u'第二十季', u'第20季')
    text2 = text2.replace(u'第二十一季', u'第21季')
    text2 = text2.replace(u'第二十二季', u'第22季')
    text2 = text2.replace(u'第二十三季', u'第23季')
    text2 = text2.replace(u'第二十四季', u'第24季')
    text2 = text2.replace(u'第二十五季', u'第25季')
    text2 = text2.replace(u'第二十六季', u'第26季')
    text2 = text2.replace(u'第二十七季', u'第27季')
    text2 = text2.replace(u'第二十八季', u'第28季')
    text2 = text2.replace(u'第二十九季', u'第29季')
    text2 = text2.replace(u'第三十季', u'第30季')
    text2 = text2.replace(u'第三十一季', u'第31季')
    text2 = text2.replace(u'第三十二季', u'第32季')
    text2 = text2.replace(u'第三十三季', u'第33季')
    text2 = text2.replace(u'第三十四季', u'第34季')
    text2 = text2.replace(u'第三十五季', u'第35季')
    text2 = text2.replace(u'第三十六季', u'第36季')
    text2 = text2.replace(u'第三十七季', u'第37季')
    text2 = text2.replace(u'第三十八季', u'第38季')
    text2 = text2.replace(u'第三十九季', u'第39季')
    text2 = text2.replace(u'第四十季', u'第40季')

    text2 = text2.replace(u'第一部', u'第1部')
    text2 = text2.replace(u'第二部', u'第2部')
    text2 = text2.replace(u'第三部', u'第3部')
    text2 = text2.replace(u'第四部', u'第4部')
    text2 = text2.replace(u'第五部', u'第5部')
    text2 = text2.replace(u'第六部', u'第6部')
    text2 = text2.replace(u'第七部', u'第7部')
    text2 = text2.replace(u'第八部', u'第8部')
    text2 = text2.replace(u'第九部', u'第9部')
    text2 = text2.replace(u'第十部', u'第10部')
    text2 = text2.replace(u'第十一部', u'第11部')
    text2 = text2.replace(u'第十二部', u'第12部')
    text2 = text2.replace(u'第十三部', u'第13部')
    text2 = text2.replace(u'第十四部', u'第14部')
    text2 = text2.replace(u'第十五部', u'第15部')
    text2 = text2.replace(u'第十六部', u'第16部')
    text2 = text2.replace(u'第十七部', u'第17部')
    text2 = text2.replace(u'第十八部', u'第18部')
    text2 = text2.replace(u'第十九部', u'第19部')
    text2 = text2.replace(u'第二十部', u'第20部')
    text2 = text2.replace(u'第二十一部', u'第21部')
    text2 = text2.replace(u'第二十二部', u'第22部')
    text2 = text2.replace(u'第二十三部', u'第23部')
    text2 = text2.replace(u'第二十四部', u'第24部')
    text2 = text2.replace(u'第二十五部', u'第25部')
    text2 = text2.replace(u'第二十六部', u'第26部')
    text2 = text2.replace(u'第二十七部', u'第27部')
    text2 = text2.replace(u'第二十八部', u'第28部')
    text2 = text2.replace(u'第二十九部', u'第29部')
    text2 = text2.replace(u'第三十部', u'第30部')
    text2 = text2.replace(u'第三十一部', u'第31部')
    text2 = text2.replace(u'第三十二部', u'第32部')
    text2 = text2.replace(u'第三十三部', u'第33部')
    text2 = text2.replace(u'第三十四部', u'第34部')
    text2 = text2.replace(u'第三十五部', u'第35部')
    text2 = text2.replace(u'第三十六部', u'第36部')
    text2 = text2.replace(u'第三十七部', u'第37部')
    text2 = text2.replace(u'第三十八部', u'第38部')
    text2 = text2.replace(u'第三十九部', u'第39部')
    text2 = text2.replace(u'第四十部', u'第40部')

    text2 = text2.replace(u'第一期', u'第1期')
    text2 = text2.replace(u'第二期', u'第2期')
    text2 = text2.replace(u'第三期', u'第3期')
    text2 = text2.replace(u'第四期', u'第4期')
    text2 = text2.replace(u'第五期', u'第5期')
    text2 = text2.replace(u'第六期', u'第6期')
    text2 = text2.replace(u'第七期', u'第7期')
    text2 = text2.replace(u'第八期', u'第8期')
    text2 = text2.replace(u'第九期', u'第9期')
    text2 = text2.replace(u'第十期', u'第10期')
    text2 = text2.replace(u'第十一期', u'第11期')
    text2 = text2.replace(u'第十二期', u'第12期')
    text2 = text2.replace(u'第十三期', u'第13期')
    text2 = text2.replace(u'第十四期', u'第14期')
    text2 = text2.replace(u'第十五期', u'第15期')
    text2 = text2.replace(u'第十六期', u'第16期')
    text2 = text2.replace(u'第十七期', u'第17期')
    text2 = text2.replace(u'第十八期', u'第18期')
    text2 = text2.replace(u'第十九期', u'第19期')
    text2 = text2.replace(u'第二十期', u'第20期')
    text2 = text2.replace(u'第二十一期', u'第21期')
    text2 = text2.replace(u'第二十二期', u'第22期')
    text2 = text2.replace(u'第二十三期', u'第23期')
    text2 = text2.replace(u'第二十四期', u'第24期')
    text2 = text2.replace(u'第二十五期', u'第25期')
    text2 = text2.replace(u'第二十六期', u'第26期')
    text2 = text2.replace(u'第二十七期', u'第27期')
    text2 = text2.replace(u'第二十八期', u'第28期')
    text2 = text2.replace(u'第二十九期', u'第29期')
    text2 = text2.replace(u'第三十期', u'第30期')
    text2 = text2.replace(u'第三十一期', u'第31期')
    text2 = text2.replace(u'第三十二期', u'第32期')
    text2 = text2.replace(u'第三十三期', u'第33期')
    text2 = text2.replace(u'第三十四期', u'第34期')
    text2 = text2.replace(u'第三十五期', u'第35期')
    text2 = text2.replace(u'第三十六期', u'第36期')
    text2 = text2.replace(u'第三十七期', u'第37期')
    text2 = text2.replace(u'第三十八期', u'第38期')
    text2 = text2.replace(u'第三十九期', u'第39期')
    text2 = text2.replace(u'第四十期', u'第40期')

    text2 = text2.replace(u'第一届', u'第1届')
    text2 = text2.replace(u'第二届', u'第2届')
    text2 = text2.replace(u'第三届', u'第3届')
    text2 = text2.replace(u'第四届', u'第4届')
    text2 = text2.replace(u'第五届', u'第5届')
    text2 = text2.replace(u'第六届', u'第6届')
    text2 = text2.replace(u'第七届', u'第7届')
    text2 = text2.replace(u'第八届', u'第8届')
    text2 = text2.replace(u'第九届', u'第9届')
    text2 = text2.replace(u'第十届', u'第10届')
    text2 = text2.replace(u'第十一届', u'第11届')
    text2 = text2.replace(u'第十二届', u'第12届')
    text2 = text2.replace(u'第十三届', u'第13届')
    text2 = text2.replace(u'第十四届', u'第14届')
    text2 = text2.replace(u'第十五届', u'第15届')
    text2 = text2.replace(u'第十六届', u'第16届')
    text2 = text2.replace(u'第十七届', u'第17届')
    text2 = text2.replace(u'第十八届', u'第18届')
    text2 = text2.replace(u'第十九届', u'第19届')
    text2 = text2.replace(u'第二十届', u'第20届')
    text2 = text2.replace(u'第二十一届', u'第21届')
    text2 = text2.replace(u'第二十二届', u'第22届')
    text2 = text2.replace(u'第二十三届', u'第23届')
    text2 = text2.replace(u'第二十四届', u'第24届')
    text2 = text2.replace(u'第二十五届', u'第25届')
    text2 = text2.replace(u'第二十六届', u'第26届')
    text2 = text2.replace(u'第二十七届', u'第27届')
    text2 = text2.replace(u'第二十八届', u'第28届')
    text2 = text2.replace(u'第二十九届', u'第29届')
    text2 = text2.replace(u'第三十届', u'第30届')
    text2 = text2.replace(u'第三十一届', u'第31届')
    text2 = text2.replace(u'第三十二届', u'第32届')
    text2 = text2.replace(u'第三十三届', u'第33届')
    text2 = text2.replace(u'第三十四届', u'第34届')
    text2 = text2.replace(u'第三十五届', u'第35届')
    text2 = text2.replace(u'第三十六届', u'第36届')
    text2 = text2.replace(u'第三十七届', u'第37届')
    text2 = text2.replace(u'第三十八届', u'第38届')
    text2 = text2.replace(u'第三十九届', u'第39届')
    text2 = text2.replace(u'第四十届', u'第40届')

    text2 = text2.replace(u'第一章', u'第1章')
    text2 = text2.replace(u'第二章', u'第2章')
    text2 = text2.replace(u'第三章', u'第3章')
    text2 = text2.replace(u'第四章', u'第4章')
    text2 = text2.replace(u'第五章', u'第5章')
    text2 = text2.replace(u'第六章', u'第6章')
    text2 = text2.replace(u'第七章', u'第7章')
    text2 = text2.replace(u'第八章', u'第8章')
    text2 = text2.replace(u'第九章', u'第9章')
    text2 = text2.replace(u'第十章', u'第10章')
    text2 = text2.replace(u'第十一章', u'第11章')
    text2 = text2.replace(u'第十二章', u'第12章')
    text2 = text2.replace(u'第十三章', u'第13章')
    text2 = text2.replace(u'第十四章', u'第14章')
    text2 = text2.replace(u'第十五章', u'第15章')
    text2 = text2.replace(u'第十六章', u'第16章')
    text2 = text2.replace(u'第十七章', u'第17章')
    text2 = text2.replace(u'第十八章', u'第18章')
    text2 = text2.replace(u'第十九章', u'第19章')
    text2 = text2.replace(u'第二十章', u'第20章')
    text2 = text2.replace(u'第二十一章', u'第21章')
    text2 = text2.replace(u'第二十二章', u'第22章')
    text2 = text2.replace(u'第二十三章', u'第23章')
    text2 = text2.replace(u'第二十四章', u'第24章')
    text2 = text2.replace(u'第二十五章', u'第25章')
    text2 = text2.replace(u'第二十六章', u'第26章')
    text2 = text2.replace(u'第二十七章', u'第27章')
    text2 = text2.replace(u'第二十八章', u'第28章')
    text2 = text2.replace(u'第二十九章', u'第29章')
    text2 = text2.replace(u'第三十章', u'第30章')
    text2 = text2.replace(u'第三十一章', u'第31章')
    text2 = text2.replace(u'第三十二章', u'第32章')
    text2 = text2.replace(u'第三十三章', u'第33章')
    text2 = text2.replace(u'第三十四章', u'第34章')
    text2 = text2.replace(u'第三十五章', u'第35章')
    text2 = text2.replace(u'第三十六章', u'第36章')
    text2 = text2.replace(u'第三十七章', u'第37章')
    text2 = text2.replace(u'第三十八章', u'第38章')
    text2 = text2.replace(u'第三十九章', u'第39章')
    text2 = text2.replace(u'第四十章', u'第40章')

    text2 = text2.replace(u'第一弹', u'第1弹')
    text2 = text2.replace(u'第二弹', u'第2弹')
    text2 = text2.replace(u'第三弹', u'第3弹')
    text2 = text2.replace(u'第四弹', u'第4弹')
    text2 = text2.replace(u'第五弹', u'第5弹')
    text2 = text2.replace(u'第六弹', u'第6弹')
    text2 = text2.replace(u'第七弹', u'第7弹')
    text2 = text2.replace(u'第八弹', u'第8弹')
    text2 = text2.replace(u'第九弹', u'第9弹')
    text2 = text2.replace(u'第十弹', u'第10弹')
    text2 = text2.replace(u'第十一弹', u'第11弹')
    text2 = text2.replace(u'第十二弹', u'第12弹')
    text2 = text2.replace(u'第十三弹', u'第13弹')
    text2 = text2.replace(u'第十四弹', u'第14弹')
    text2 = text2.replace(u'第十五弹', u'第15弹')
    text2 = text2.replace(u'第十六弹', u'第16弹')
    text2 = text2.replace(u'第十七弹', u'第17弹')
    text2 = text2.replace(u'第十八弹', u'第18弹')
    text2 = text2.replace(u'第十九弹', u'第19弹')
    text2 = text2.replace(u'第二十弹', u'第20弹')
    text2 = text2.replace(u'第二十一弹', u'第21弹')
    text2 = text2.replace(u'第二十二弹', u'第22弹')
    text2 = text2.replace(u'第二十三弹', u'第23弹')
    text2 = text2.replace(u'第二十四弹', u'第24弹')
    text2 = text2.replace(u'第二十五弹', u'第25弹')
    text2 = text2.replace(u'第二十六弹', u'第26弹')
    text2 = text2.replace(u'第二十七弹', u'第27弹')
    text2 = text2.replace(u'第二十八弹', u'第28弹')
    text2 = text2.replace(u'第二十九弹', u'第29弹')
    text2 = text2.replace(u'第三十弹', u'第30弹')
    text2 = text2.replace(u'第三十一弹', u'第31弹')
    text2 = text2.replace(u'第三十二弹', u'第32弹')
    text2 = text2.replace(u'第三十三弹', u'第33弹')
    text2 = text2.replace(u'第三十四弹', u'第34弹')
    text2 = text2.replace(u'第三十五弹', u'第35弹')
    text2 = text2.replace(u'第三十六弹', u'第36弹')
    text2 = text2.replace(u'第三十七弹', u'第37弹')
    text2 = text2.replace(u'第三十八弹', u'第38弹')
    text2 = text2.replace(u'第三十九弹', u'第39弹')
    text2 = text2.replace(u'第四十弹', u'第40弹')

    text2 = text2.replace(u'第一集', u'第1集')
    text2 = text2.replace(u'第二集', u'第2集')
    text2 = text2.replace(u'第三集', u'第3集')
    text2 = text2.replace(u'第四集', u'第4集')
    text2 = text2.replace(u'第五集', u'第5集')
    text2 = text2.replace(u'第六集', u'第6集')
    text2 = text2.replace(u'第七集', u'第7集')
    text2 = text2.replace(u'第八集', u'第8集')
    text2 = text2.replace(u'第九集', u'第9集')
    text2 = text2.replace(u'第十集', u'第10集')
    text2 = text2.replace(u'第十一集', u'第11集')
    text2 = text2.replace(u'第十二集', u'第12集')
    text2 = text2.replace(u'第十三集', u'第13集')
    text2 = text2.replace(u'第十四集', u'第14集')
    text2 = text2.replace(u'第十五集', u'第15集')
    text2 = text2.replace(u'第十六集', u'第16集')
    text2 = text2.replace(u'第十七集', u'第17集')
    text2 = text2.replace(u'第十八集', u'第18集')
    text2 = text2.replace(u'第十九集', u'第19集')
    text2 = text2.replace(u'第二十集', u'第20集')
    text2 = text2.replace(u'第二十一集', u'第21集')
    text2 = text2.replace(u'第二十二集', u'第22集')
    text2 = text2.replace(u'第二十三集', u'第23集')
    text2 = text2.replace(u'第二十四集', u'第24集')
    text2 = text2.replace(u'第二十五集', u'第25集')
    text2 = text2.replace(u'第二十六集', u'第26集')
    text2 = text2.replace(u'第二十七集', u'第27集')
    text2 = text2.replace(u'第二十八集', u'第28集')
    text2 = text2.replace(u'第二十九集', u'第29集')
    text2 = text2.replace(u'第三十集', u'第30集')
    text2 = text2.replace(u'第三十一集', u'第31集')
    text2 = text2.replace(u'第三十二集', u'第32集')
    text2 = text2.replace(u'第三十三集', u'第33集')
    text2 = text2.replace(u'第三十四集', u'第34集')
    text2 = text2.replace(u'第三十五集', u'第35集')
    text2 = text2.replace(u'第三十六集', u'第36集')
    text2 = text2.replace(u'第三十七集', u'第37集')
    text2 = text2.replace(u'第三十八集', u'第38集')
    text2 = text2.replace(u'第三十九集', u'第39集')
    text2 = text2.replace(u'第四十集', u'第40集')
    text2 = text2.replace(u'第四十一集', u'第41集')
    text2 = text2.replace(u'第四十二集', u'第42集')
    text2 = text2.replace(u'第四十三集', u'第43集')
    text2 = text2.replace(u'第四十四集', u'第44集')
    text2 = text2.replace(u'第四十五集', u'第45集')
    text2 = text2.replace(u'第四十六集', u'第46集')
    text2 = text2.replace(u'第四十七集', u'第47集')
    text2 = text2.replace(u'第四十八集', u'第48集')
    text2 = text2.replace(u'第四十九集', u'第49集')
    text2 = text2.replace(u'第五十集', u'第50集')
    text2 = text2.replace(u'第五十一集', u'第51集')
    text2 = text2.replace(u'第五十二集', u'第52集')
    text2 = text2.replace(u'第五十三集', u'第53集')
    text2 = text2.replace(u'第五十四集', u'第54集')
    text2 = text2.replace(u'第五十五集', u'第55集')
    text2 = text2.replace(u'第五十六集', u'第56集')
    text2 = text2.replace(u'第五十七集', u'第57集')
    text2 = text2.replace(u'第五十八集', u'第58集')
    text2 = text2.replace(u'第五十九集', u'第59集')
    text2 = text2.replace(u'第六十集', u'第60集')

    return text2


if __name__ == '__main__':
    with open('/Users/tanzhen/Desktop/code/odps/bin/qt_test_corpus_adjust', 'r') as f:
        for text in f:
            text = text.decode('utf8')

            text2 = text
            text2 = parse_season(text2)

            res_list.append(text2.encode('utf8'))

    with open('/Users/tanzhen/Desktop/code/odps/bin/qt_test_corpus_adjust2', 'w') as f:
        for s in res_list:
            f.write(s)

    res_list = []
    with open('/Users/tanzhen/Desktop/code/odps/bin/qt_train_corpus_adjust', 'r') as f:
        for text in f:
            text = text.decode('utf8')

            text2 = text
            text2 = parse_season(text2)

            res_list.append(text2.encode('utf8'))

    with open('/Users/tanzhen/Desktop/code/odps/bin/qt_train_corpus_adjust2', 'w') as f:
        for s in res_list:
            f.write(s)